pipeline {
    agent any
    environment {
        KUBECONFIG = '"C:/Users/Dell/.kube/config"'
    }
    stages{
        stage('Build Maven'){
            steps{
                checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://a96abhinav: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@github.com/a96abhinav/my-config-server.git']])
                bat 'mvn clean install'
            }
        }
        stage('Build Docker Image'){
            steps{
                script{
                    bat 'docker build -t a96abhinav/my-config-server-app:latest .'
                }
            }
        }
        stage('Push Image to DockerHub') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'dockerhub_pass', variable: 'dockerhub_pass')]) {
                        bat 'docker login -u a96abhinav -p %dockerhub_pass% '
                        bat 'docker push a96abhinav/my-config-server-app:latest'
                    }
                }

            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                script {
                    def deploymentExists = bat(script: 'kubectl get deployment my-config-server-app >nul 2>&1', returnStatus: true) == 0

                    if (deploymentExists) {
                        echo 'Deployment exists. Deleting...'
                        bat 'kubectl delete -f deployment.yaml'
                    } else {
                        echo 'Deployment does not exist.'
                    }

                    bat 'kubectl apply -f deployment.yaml --validate=false'
                }
            }
        }
    }
}