apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-config-server-app
  labels:
    app: my-config-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-config-server-app
  template:
    metadata:
      labels:
        app: my-config-server-app
    spec:
      containers:
        - name: my-config-server-app-container
          image: a96abhinav/my-config-server-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://my-service-registry-app-service:8761/eureka"
      imagePullSecrets:
        - name: my-docker-registry-key
---
apiVersion: v1
kind: Service
metadata:
  name: my-config-server-app-service
spec:
  selector:
    app: my-config-server-app
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
