spring:
  application:
    name: my-springboot-app
  config:
#    import: configserver:http://localhost:8888
    import: configserver:http://config-server:8888
  cloud:
   config:
    label: ${spring.profiles.active}
    fail-fast: true
    retry.initial-interval: 1000
    retry.max-interval: 2000
    retry.max-attempts: 6
  profiles:
    active: dev