apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      initContainers:
        - name: wait-for-service-registry
          image: busybox
          command: [ 'sh', '-c', 'until nc -z service-registry 8761; do sleep 5; done' ]
      containers:
        - name: config-server
          image: a96abhinav/my-springboot-microservices-config-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-registry:8761/eureka"
      imagePullSecrets:
        - name: my-docker-registry-key
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
