apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  labels:
    app: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: a96abhinav/my-springboot-microservices-service-registry:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
      imagePullSecrets:
        - name: my-docker-registry-key
---
apiVersion: v1
kind: Service
metadata:
  name: service-registry
spec:
  selector:
    app: service-registry
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer
