package com.springboot.rest.constants;

import lombok.experimental.UtilityClass;

@UtilityClass
public class QueryConstants {
	public static final String MALE_AND_FEMALE_COUNT_BY_DEPARTMENT_QUERY = "with CTE as(\r\n"
			+ "  select \r\n"
			+ "    emp_department, \r\n"
			+ "    emp_gender, \r\n"
			+ "    count(emp_gender) as count \r\n"
			+ "  from \r\n"
			+ "    employees \r\n"
			+ "  group by \r\n"
			+ "    emp_department, \r\n"
			+ "    emp_gender \r\n"
			+ "  order by \r\n"
			+ "    1\r\n"
			+ "), \r\n"
			+ "CTE1 as (\r\n"
			+ "  select \r\n"
			+ "    distinct cte.emp_department, \r\n"
			+ "    (\r\n"
			+ "      select \r\n"
			+ "        c.count \r\n"
			+ "      from \r\n"
			+ "        CTE c \r\n"
			+ "      where \r\n"
			+ "        c.emp_department = cte.emp_department \r\n"
			+ "        and c.emp_gender = 'Male' \r\n"
			+ "      LIMIT \r\n"
			+ "        1\r\n"
			+ "    ) as male_count, \r\n"
			+ "    (\r\n"
			+ "      select \r\n"
			+ "        c.count \r\n"
			+ "      from \r\n"
			+ "        CTE c \r\n"
			+ "      where \r\n"
			+ "        c.emp_department = cte.emp_department \r\n"
			+ "        and c.emp_gender = 'Female' \r\n"
			+ "      LIMIT \r\n"
			+ "        1\r\n"
			+ "    ) as female_count \r\n"
			+ "  from \r\n"
			+ "    CTE cte\r\n"
			+ ") \r\n"
			+ "select \r\n"
			+ "  emp_department, \r\n"
			+ "  coalesce(male_count, 0) as male_count, \r\n"
			+ "  coalesce(female_count, 0) as female_count \r\n"
			+ "from \r\n"
			+ "  cte1;\r\n"
			+ "";
}
