server:
 port: 8085
 servlet.context-path: /${spring.application.name}

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 224274262797-053n39inrcpfl8js8lk2pkm69d1825b1.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email, https://www.googleapis.com/auth/user.phonenumbers.read
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8085/my-springboot-app/login/oauth2/code/google"
            client-name: Google
          github:
            client-id: Ov23ctpDlwOoPUWlFbb4
            client-secret: 7628296145843c5ef2d2ea226f7dcb8922ba45fc
            scope: read:user, user:email
            redirect-uri: "http://localhost:8085/my-springboot-app/login/oauth2/code/github"
            authorization-grant-type: authorization_code
            client-name: GitHub
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

